name: Check docs

on:
  push:
    branches: ["main"]
    paths:
      - "docs/**"
  pull_request:
    branches: ["main"]
    paths:
      - "docs/**"
  workflow_dispatch:
  schedule:
    # Run every day at 7:00 AM UTC = 12:00 AM PST
    - cron: " 0  7  *  *  *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkDocs:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          persist-credentials: false
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 10.24
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          cache-dependency-path: "docs"
          node-version: "23"
          cache: "pnpm"

      - name: Build docs
        working-directory: docs
        run: |
          pnpm install
          pnpm build

      - name: Check links
        uses: lycheeverse/lychee-action@a8c4c7cb88f0c7386610c35eb25108e448569cb0 # v2
        with:
          workingDirectory: docs
          args: --user-agent 'curl/8.13.0' --no-progress --remap "https://graft.rs file://$PWD/dist" --fallback-extensions html --exclude-path "llms-.*\.txt" --root-dir $PWD/dist dist
          failIfEmpty: true
          format: markdown
          jobSummary: true
          token: ${{ secrets.GITHUB_TOKEN }}
